# Generated by Django 5.0.3 on 2024-05-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(default='', max_length=500)),
                ('head1', models.CharField(default='', max_length=500)),
                ('head2', models.IntegerField(default='', max_length=500)),
                ('pub_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
